"""initial schema

Revision ID: 2df769b63ac8
Revises: 
Create Date: 2026-03-17 09:54:46.258737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df769b63ac8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('futures_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_futures_history'))
    )
    op.create_table('live_game_state',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('commence_time', sa.String(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.String(), nullable=True),
    sa.Column('time_remaining_str', sa.String(), nullable=True),
    sa.Column('seconds_remaining', sa.Integer(), nullable=True),
    sa.Column('live_home_price', sa.Float(), nullable=True),
    sa.Column('live_home_point', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('game_id', name=op.f('pk_live_game_state'))
    )
    with op.batch_alter_table('live_game_state', schema=None) as batch_op:
        batch_op.create_index('idx_live_game_last_updated', ['last_updated'], unique=False)
        batch_op.create_index('idx_live_game_seconds_remaining', ['seconds_remaining'], unique=False)

    op.create_table('market_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_signals'))
    )
    op.create_table('odds_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('commence_time', sa.String(), nullable=False),
    sa.Column('bookmaker', sa.String(), nullable=False),
    sa.Column('market_type', sa.String(), nullable=False),
    sa.Column('home_price', sa.Float(), nullable=True),
    sa.Column('away_price', sa.Float(), nullable=True),
    sa.Column('home_point', sa.Float(), nullable=True),
    sa.Column('away_point', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_odds_history'))
    )
    with op.batch_alter_table('odds_history', schema=None) as batch_op:
        batch_op.create_index('idx_odds_game_id', ['game_id'], unique=False)

    op.create_table('opponent_defense_matrix',
    sa.Column('team_abbr', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('stat', sa.String(), nullable=False),
    sa.Column('modifier', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('team_abbr', 'position', 'stat', name=op.f('pk_opponent_defense_matrix'))
    )
    with op.batch_alter_table('opponent_defense_matrix', schema=None) as batch_op:
        batch_op.create_index('idx_opp_defense_lookup', ['team_abbr', 'position', 'stat'], unique=False)

    op.create_table('player_baselines',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('stat', sa.String(), nullable=False),
    sa.Column('per_minute_rate', sa.Float(), nullable=False),
    sa.Column('projected_minutes', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('player_id', 'stat', name=op.f('pk_player_baselines'))
    )
    with op.batch_alter_table('player_baselines', schema=None) as batch_op:
        batch_op.create_index('idx_player_baselines_player', ['player_id'], unique=False)

    op.create_table('player_positions',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_abbr', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('player_id', name=op.f('pk_player_positions'))
    )
    with op.batch_alter_table('player_positions', schema=None) as batch_op:
        batch_op.create_index('idx_player_positions_team', ['team_abbr'], unique=False)

    op.create_table('team_game_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('game_date', sa.String(), nullable=False),
    sa.Column('team_abbr', sa.String(), nullable=False),
    sa.Column('matchup', sa.String(), nullable=True),
    sa.Column('wl', sa.String(), nullable=True),
    sa.Column('pts', sa.Float(), nullable=True),
    sa.Column('opp_pts', sa.Float(), nullable=True),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.Column('efg_pct', sa.Float(), nullable=True),
    sa.Column('tov_pct', sa.Float(), nullable=True),
    sa.Column('off_rating', sa.Float(), nullable=True),
    sa.Column('def_rating', sa.Float(), nullable=True),
    sa.Column('net_rating', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), server_default='TeamGameLogs', nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_game_logs')),
    sa.UniqueConstraint('season', 'game_id', 'team_abbr', name=op.f('uq_team_game_logs_season'))
    )
    with op.batch_alter_table('team_game_logs', schema=None) as batch_op:
        batch_op.create_index('idx_team_logs_season', ['season'], unique=False)
        batch_op.create_index('idx_team_logs_team_date', ['team_abbr', 'game_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_game_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_team_logs_team_date')
        batch_op.drop_index('idx_team_logs_season')

    op.drop_table('team_game_logs')
    with op.batch_alter_table('player_positions', schema=None) as batch_op:
        batch_op.drop_index('idx_player_positions_team')

    op.drop_table('player_positions')
    with op.batch_alter_table('player_baselines', schema=None) as batch_op:
        batch_op.drop_index('idx_player_baselines_player')

    op.drop_table('player_baselines')
    with op.batch_alter_table('opponent_defense_matrix', schema=None) as batch_op:
        batch_op.drop_index('idx_opp_defense_lookup')

    op.drop_table('opponent_defense_matrix')
    with op.batch_alter_table('odds_history', schema=None) as batch_op:
        batch_op.drop_index('idx_odds_game_id')

    op.drop_table('odds_history')
    op.drop_table('market_signals')
    with op.batch_alter_table('live_game_state', schema=None) as batch_op:
        batch_op.drop_index('idx_live_game_seconds_remaining')
        batch_op.drop_index('idx_live_game_last_updated')

    op.drop_table('live_game_state')
    op.drop_table('futures_history')
    # ### end Alembic commands ###
