"""add injury impact tables

Revision ID: 541b3fc3c566
Revises: 62d60f91fc78
Create Date: 2026-03-17 11:12:13.133576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541b3fc3c566'
down_revision = '62d60f91fc78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team_abbr', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('vorp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_injuries'))
    )
    with op.batch_alter_table('daily_injuries', schema=None) as batch_op:
        batch_op.create_index('idx_daily_injuries_date', ['date'], unique=False)
        batch_op.create_index('idx_daily_injuries_team_date', ['team_abbr', 'date'], unique=False)

    op.create_table('team_injury_impact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('team_abbr', sa.String(), nullable=False),
    sa.Column('total_vorp_missing', sa.Float(), nullable=True),
    sa.Column('injury_modifier', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_injury_impact')),
    sa.UniqueConstraint('date', 'team_abbr', name=op.f('uq_team_injury_impact_date'))
    )
    with op.batch_alter_table('team_injury_impact', schema=None) as batch_op:
        batch_op.create_index('idx_team_injury_impact_date', ['date'], unique=False)
        batch_op.create_index('idx_team_injury_impact_team_date', ['team_abbr', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_injury_impact', schema=None) as batch_op:
        batch_op.drop_index('idx_team_injury_impact_team_date')
        batch_op.drop_index('idx_team_injury_impact_date')

    op.drop_table('team_injury_impact')
    with op.batch_alter_table('daily_injuries', schema=None) as batch_op:
        batch_op.drop_index('idx_daily_injuries_team_date')
        batch_op.drop_index('idx_daily_injuries_date')

    op.drop_table('daily_injuries')
    # ### end Alembic commands ###
