"""add context enrichment tables

Revision ID: 62d60f91fc78
Revises: 2df769b63ac8
Create Date: 2026-03-17 10:32:43.603654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d60f91fc78'
down_revision = '2df769b63ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referee_game_logs',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=False),
    sa.Column('official_name', sa.String(), nullable=False),
    sa.Column('game_date', sa.String(), nullable=True),
    sa.Column('home_team', sa.String(), nullable=True),
    sa.Column('away_team', sa.String(), nullable=True),
    sa.Column('home_win', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Float(), nullable=True),
    sa.Column('total_fouls', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('game_id', 'official_id', name=op.f('pk_referee_game_logs'))
    )
    with op.batch_alter_table('referee_game_logs', schema=None) as batch_op:
        batch_op.create_index('idx_ref_game_logs_date', ['game_date'], unique=False)
        batch_op.create_index('idx_ref_game_logs_official', ['official_id'], unique=False)

    op.create_table('referee_stats',
    sa.Column('official_id', sa.Integer(), nullable=False),
    sa.Column('official_name', sa.String(), nullable=False),
    sa.Column('games_officiated', sa.Integer(), nullable=True),
    sa.Column('home_win_pct', sa.Float(), nullable=True),
    sa.Column('avg_total_points', sa.Float(), nullable=True),
    sa.Column('avg_fouls_called', sa.Float(), nullable=True),
    sa.Column('over_index', sa.Float(), nullable=True),
    sa.Column('home_bias', sa.Float(), nullable=True),
    sa.Column('last_game_date', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('official_id', name=op.f('pk_referee_stats'))
    )
    op.create_table('team_injury_status',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_abbr', sa.String(), nullable=False),
    sa.Column('game_date', sa.String(), nullable=True),
    sa.Column('inactive_player_ids', sa.String(), nullable=True),
    sa.Column('inactive_player_names', sa.String(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('active_value', sa.Float(), nullable=True),
    sa.Column('injury_impact', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('game_id', 'team_abbr', name=op.f('pk_team_injury_status'))
    )
    with op.batch_alter_table('team_injury_status', schema=None) as batch_op:
        batch_op.create_index('idx_team_injury_date', ['game_date'], unique=False)
        batch_op.create_index('idx_team_injury_team_date', ['team_abbr', 'game_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_injury_status', schema=None) as batch_op:
        batch_op.drop_index('idx_team_injury_team_date')
        batch_op.drop_index('idx_team_injury_date')

    op.drop_table('team_injury_status')
    op.drop_table('referee_stats')
    with op.batch_alter_table('referee_game_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_ref_game_logs_official')
        batch_op.drop_index('idx_ref_game_logs_date')

    op.drop_table('referee_game_logs')
    # ### end Alembic commands ###
